### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by Bluscream**
Now using the v2 version when installing from v2 branch's repo

### CODE REVIEW

**Comment by AdorablePotato** [comment]
Thank you

**Comment by Bluscream** [comment]
Why didn't you merge it?

**Comment by AdorablePotato** [comment]
It's merged: https://github.com/benediktschmitt/py-ts3/commits/v2/README.rst

**Comment by Bluscream** [comment]
Strange, it shows closed to me and doesn't acknowledge me as contributor :/

**Pull request closed without merging**
